version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      - celery
    environment:
      - DATABASE_URL=postgres://postgres:root123@db:5432/image_processing
    command: >
      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: image_processing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123

  redis:
    image: redis:latest

  celery:
    build: .
    command: celery -A server worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
